### ISSUE TITLE
providing `text_file` always results in _(NO MSG FILE)_

### ISSUE THREAD

**Issue by cah-tyler-rasor** [navicore/teams-notification-resource#14]
in #13 we added the ability to pass in a reference to a `text_file` produced by a previous job, but this always results in a `_(NO MSG FILE)_` message

```yaml
resource_types:
- name: teams-notification
  type: registry-image
  source:
    repository: navicore/teams-notification-resource
    tag: v0.9.4

resources:
- name: teams-notification
  type: teams-notification
  source:
    url: ((webhook-url))

jobs:
- name: test-text-file
  plan:
  - task: generate-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: alpine }
      outputs:
      - name: output
      run:
        path: sh
        args:
        - -exc
        - echo "test" > output/text_file
  - put: teams-notification
    params:
      text_file: output/text_file
      title: testing text file
```

![image](https://user-images.githubusercontent.com/37845333/114944677-0e38ba80-9e16-11eb-81ca-394566ccc448.png)
