### ISSUE TITLE
Bad payload received by generic incoming webhook

### ISSUE THREAD

**Issue by achille1789** [navicore/teams-notification-resource#41]
Hi,
I tried to use your resource today for the first time and I am getting: error code 400 - Bad payload received by generic incoming webhook
I am running your [test pipeline](https://github.com/navicore/teams-notification-resource/blob/main/testing/hello-world.yml) with my webhook url.
I tried to use my webhook on Postman and it worked.
I saw that you recently closed a similar issues, so as you suggested there, I tried to use tag v0.9.9 instead of "latest" but Concourse shows this error "version is missing from previous step".
I tried also to use v0.9.7 but I am getting the same error code 400.

Do you have any suggestion?
Thanks

**Comment by navicore** [comment]
The 400 error will come from any build earlier than v0.9.9 so you need to use that tag or a fresh pull of "latest".  I suspect you have a cached copy of an older image under the "latest" tag.

When you got the error changing to v0.9.9, did you change the resource type def?

```
resource_types:

- name: teams-notification
  type: docker-image
  source:
    repository: navicore/teams-notification-resource
    tag: v0.9.9
 ```
 
 If you still get 400 http errors after using v0.9.9 then you've encountered a new bug and we'll work on that but so far everyone that has hit the 400 error has seen it fixed with v0.9.9.
